// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookListing struct {
	ID          string  `json:"id"`
	Bookname    string  `json:"bookname"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Author      string  `json:"author"`
	AddedOn     float64 `json:"addedOn"`
}

type DeleteBook struct {
	DeletedBookID string `json:"DeletedBookID"`
	Token         string `json:"token"`
}

type NewBookListing struct {
	Title       string `json:"title"`
	Bookname    string `json:"bookname"`
	Description string `json:"description"`
	Author      string `json:"author"`
}

type UpdateBookListing struct {
	Bookname    *string `json:"bookname,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Author      *string `json:"author,omitempty"`
}
